name: Django CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  SECRET_KEY: ci-test

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install wheel
        pip install -r requirements_dev.txt
    - name: Run Tests
      run: |
        python manage.py test


    # Run linters and Django related checks
    - name: Run Linters and Checks
      run: |
        pre-commit run --all
      if: ${{ always() }}
